services:
  ml:
    build: ./ml
    ports:
      - "10001:8080"
  yt:
    build: ./yt-backend
    ports:
      - "10002:8080"
  reddit:
    build: ./reddit-backend
    ports:
      - "10003:8080"
  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
