[project]
name = "magus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dotenv","pandas","numpy","google-api-python-client","pydantic","vaderSentiment","matplotlib"]


